name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  carousel_slider: ^4.2.0
  url_launcher: ^6.1.5
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.6
  table_calendar: ^3.2.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons: # 👈 เพิ่มด้านล่างสุดของไฟล์
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"