// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvdpJmFPX24vGVJuKtCW0SgAvMaMyUI3M',
    appId: '1:856666931848:web:b0787f9bf885413906553d',
    messagingSenderId: '856666931848',
    projectId: 'watertrackerprod',
    authDomain: 'watertrackerprod.firebaseapp.com',
    storageBucket: 'watertrackerprod.firebasestorage.app',
    measurementId: 'G-FPGJY3PYX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0ikCaOohGNQASSlzt5kVirkAksVHF7c',
    appId: '1:856666931848:android:403e3c3cb1fe49c506553d',
    messagingSenderId: '856666931848',
    projectId: 'watertrackerprod',
    storageBucket: 'watertrackerprod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMBLQuu-Sr4lXA-SLBRbQmX2836kwLSSw',
    appId: '1:856666931848:ios:b7c891e26886f21806553d',
    messagingSenderId: '856666931848',
    projectId: 'watertrackerprod',
    storageBucket: 'watertrackerprod.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMBLQuu-Sr4lXA-SLBRbQmX2836kwLSSw',
    appId: '1:856666931848:ios:b7c891e26886f21806553d',
    messagingSenderId: '856666931848',
    projectId: 'watertrackerprod',
    storageBucket: 'watertrackerprod.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvdpJmFPX24vGVJuKtCW0SgAvMaMyUI3M',
    appId: '1:856666931848:web:2c9273b38835afd406553d',
    messagingSenderId: '856666931848',
    projectId: 'watertrackerprod',
    authDomain: 'watertrackerprod.firebaseapp.com',
    storageBucket: 'watertrackerprod.firebasestorage.app',
    measurementId: 'G-D2STERREFP',
  );

}