// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVAZeZIwkdYWomRcDwvRsBJ37LAtd9j7I',
    appId: '1:1044106237234:web:c79b8a87f6a19777e1732b',
    messagingSenderId: '1044106237234',
    projectId: 'watertracker-4e37f',
    authDomain: 'watertracker-4e37f.firebaseapp.com',
    databaseURL: 'https://watertracker-4e37f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertracker-4e37f.firebasestorage.app',
    measurementId: 'G-9XE9HWMPE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuHPVJszJCwPLoFnoHPMVk09SgG2sQ3E',
    appId: '1:1044106237234:android:71e5e7dfcdb592bce1732b',
    messagingSenderId: '1044106237234',
    projectId: 'watertracker-4e37f',
    databaseURL: 'https://watertracker-4e37f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertracker-4e37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2jaT8yzCv5QWJdvipApAeT0YSj0xLPY',
    appId: '1:1044106237234:ios:d9feef16dc2c4eebe1732b',
    messagingSenderId: '1044106237234',
    projectId: 'watertracker-4e37f',
    databaseURL: 'https://watertracker-4e37f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertracker-4e37f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2jaT8yzCv5QWJdvipApAeT0YSj0xLPY',
    appId: '1:1044106237234:ios:d9feef16dc2c4eebe1732b',
    messagingSenderId: '1044106237234',
    projectId: 'watertracker-4e37f',
    databaseURL: 'https://watertracker-4e37f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertracker-4e37f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVAZeZIwkdYWomRcDwvRsBJ37LAtd9j7I',
    appId: '1:1044106237234:web:c8b6157694f6022fe1732b',
    messagingSenderId: '1044106237234',
    projectId: 'watertracker-4e37f',
    authDomain: 'watertracker-4e37f.firebaseapp.com',
    databaseURL: 'https://watertracker-4e37f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertracker-4e37f.firebasestorage.app',
    measurementId: 'G-YRG1L5YJ41',
  );
}
